# PyTorch Tensors 

In [1]:
%matplotlib inline
import torch
import numpy as np

Tensors are a specialized data structure that are very similar to arrays and matrices.

Numpy arrays and Torch are alike

In [9]:
v = [[1, 2],[3, 4]]
x_data = torch.tensor(v)
print(x_data)

np_array = np.array(v)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])


In [4]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.0081, 0.1626],
        [0.2152, 0.9130]]) 



In [5]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0220, 0.5692, 0.3254],
        [0.4056, 0.6404, 0.0292]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [15]:
#  random tensor
tensor = torch.rand(3,4)
print(tensor)
print(f"\nShape of tensor: \n{tensor.shape}, \
      {tensor.dtype}, \
      {tensor.device}")

tensor([[0.7573, 0.3509, 0.5836, 0.3394],
        [0.3505, 0.8346, 0.4507, 0.4440],
        [0.4477, 0.5730, 0.0577, 0.9101]])

Shape of tensor: 
torch.Size([3, 4]),       torch.float32,       cpu


## Numpy-like Slice & Indexing

In [20]:
tensor = torch.ones(4, 4)
print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])

# modify a column, setting to 0 
tensor[:,1] = 99
print('\n',tensor) 

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])

 tensor([[ 1., 99.,  1.,  1.],
        [ 1., 99.,  1.,  1.],
        [ 1., 99.,  1.,  1.],
        [ 1., 99.,  1.,  1.]])


## torch.cat and torch.stack

In [24]:
tensor = torch.ones(3,3)
print(f'tensor array: \n{tensor}')

torchedCat = torch.cat([tensor, tensor], dim=1)
print(f'torchedCat :\n{torchedCat}')

tensor array: 
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torchedCat :
tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


In [25]:
tstack = torch.stack([tensor, tensor])
tstack

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [27]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [29]:
# sum values in a tensor
sumValues = tensor.sum()
print(sumValues)
aggValues = sumValues.item() # aggregate value by itself
print(aggValues)

tensor(9.)
9.0


In [30]:
print(tensor, "\n")
tensor.add_(95)
print(tensor) # perm change

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

tensor([[96., 96., 96.],
        [96., 96., 96.],
        [96., 96., 96.]])


In [31]:
tensor

tensor([[96., 96., 96.],
        [96., 96., 96.],
        [96., 96., 96.]])